[package]
name = "headless-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Configuration and subscription logic for the Mihomo headless service"

[dependencies]
anyhow.workspace = true
clash-verge-draft.workspace = true
clash-verge-limiter.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
smartstring.workspace = true
url = "2.5.8"
percent-encoding = "2.3.2"
boa_engine = "=0.22.0"
serde_json.workspace = true
ring = "=0.17.14"

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"

[dev-dependencies]
anyhow.workspace = true
